language: r
warnings_are_errors: false
r:
  - oldrel
  - release
  - devel
apt_packages:
  - libgdal1-dev
  - libproj-dev
  - libudunits2-dev
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'covr::codecov()'
